CREATE TABLE IF NOT EXISTS `role_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(32) NOT NULL,
  `permission` VARCHAR(32) NOT NULL,
  INDEX (`key`),
  FOREIGN KEY (`key`) REFERENCES roles(`key`) ON DELETE CASCADE ON UPDATE CASCADE
);