CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(24) NOT NULL,
  `identifier` VARCHAR(24) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `allowlisted` TINYINT NOT NULL DEFAULT 0,
  `priority` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_played_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(`identifier`)
);